### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by willwestwood** [siphontv/p2ptv#7]
Do you have a fix for a memory leak?

I can't seem to pinpoint the issue.

I'm using Chrome to play the video

**Comment by eadle** [comment]
Hmm... what version of node and chrome? How are you testing for memory leaks? Any additional output would be helpful, but it is possible that I just pushed data to the browser willy-nilly since I was concerned with building the distribution network at the time.

**Comment by willwestwood** [comment]
Using the latest version of node and chrome.

I think I found 2 fixes to address the memory leaks, in the client side p2ptv.js:
Fix 1: between lines 587 and 588, I inserted the line

stream.sourceBuffer.remove(0, stream.sourceBuffer.timestampOffset-1);

which removes all the previous media segments which are no longer used.

Fix 2: replaced lines 1184 to 1201 with:

```
if (chunk.timecode != currTimeCode) {
  currMediaSegment = new P2PTV.MediaSegment(chunk);
  currTimeCode = chunk.timecode;
  stream.timecodeQueue.push(chunk.timecode);
} else {
  currMediaSegment.addChunk(chunk);
}

if (currMediaSegment.isComplete()) {
  self._player.appendMediaSegment(
    currMediaSegment.getBlob(),
    chunk.timecode
  );
}
```

where currMediaSegment and currTimeCode are new variables, which removes the need for a hash array.

**Comment by eadle** [comment]
Nice. Want to make a pull request? The first fix is in src/client/MediaPlayer.js and the second in src/client/PushPullWindow.js. You can build the p2ptv.js file with grunt.

**Comment by eadle** [comment]
The first fix appears to clear media segments in the buffer that still may be playing.

**Comment by eadle** [comment]
**84756aebc9ba90a4c2a120dfd767a0f4972d2068** fixes sourcebuffer memory leak. Haven't pushed a new version yet though. Probably won't until after the other memory leak is fixed.

Edit:
00b5b68083d9c813f13b2d59030ae08d42c267cd appears to fix the 2nd major memory leak that you mentioned. I took 25 memory snapshots over 30 minutes and it's averaged at 6MB and currently sitting at 4.9MB (instead of 150-200MB before fix). I didn't realize it was that bad. Thanks a lot for pointing this out.

I'll leave this open for a week or two to verify the fix.
